### ISSUE TITLE
Error message in RO package

### ISSUE THREAD

**Issue by chyan26** [Subaru-PFS/tron_actorcore#4]
I am having hard time when playing with hubclient on a newly installed Ubuntu 14.04.  I got the following error messages when starting hubclient.

---------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/chyan/mhs/devel/tron_actorcore/bin/hubclient", line 177, in <module>
    client = TCPClient(root, addr, port, cmdrName=cmdrName)
  File "/home/chyan/mhs/devel/tron_actorcore/bin/hubclient", line 74, in __init__
    self.doCmd('hub setUsername %s' % (self.cmdrName))
  File "/home/chyan/mhs/devel/tron_actorcore/bin/hubclient", line 115, in doCmd
    self.conn.writeLine(cmd)
  File "/home/chyan/mhs/devel/tron_actorcore/python/RO/Comm/TCPConnection.py", line 285, in writeLine
    self._sock.writeLine(astr)
  File "/home/chyan/mhs/devel/tron_actorcore/python/RO/Comm/TkSocket.py", line 458, in writeLine
    raise RuntimeError("%s not connected" % (self,))
RuntimeError: TkSocket None not connected
---------------------------------------------------------------------------

I am able to remove this error message by edit the line 350 in RO/Comm/TkSocket.py from sockArgs = ('-async', addr, port) to sockArgs = (addr, port).   However, the fpsActor (or pficsActor) won't be able to connect to the MHS after the modification.

**Comment by chyan26** [comment]
After the testing, we are able to get rid of this problem by using Ubuntu 16.04 Desktop version.
